# Question 2: Library Inventory Management (Pandas)

## 1. DataFrame Creation

In [8]:
import pandas as pd

data = {
    "Key": ["Book1", "Book2", "Book3", "Book4", "Book5"],
    "Title": [
        "The Great Gatsby",
        "To Kill a Mockingbird",
        "1984",
        "Pride and Prejudice",
        "The Catcher in the Rye"
    ],
    "Author": [
        "F. Scott Fitzgerald",
        "Harper Lee",
        "George Orwell",
        "Jane Austen",
        "J.D. Salinger"
    ],
    "Year": [1925, 1960, 1949, 1813, 1951],
    "Availability": [True, False, True, True, True]
}

library_df = pd.DataFrame(data)
library_df.set_index("Key", inplace=True)
library_df

                        Title               Author  Year  Availability
Key
Book1        The Great Gatsby  F. Scott Fitzgerald  1925          True
Book2   To Kill a Mockingbird           Harper Lee  1960         False
Book3                    1984        George Orwell  1949          True
Book4     Pride and Prejudice          Jane Austen  1813          True
Book5  The Catcher in the Rye        J.D. Salinger  1951          True

## 2. Updating Data

In [5]:
library_df.loc["Book2", "Availability"] = True

library_df

                        Title               Author  Year  Availability
Key
Book1        The Great Gatsby  F. Scott Fitzgerald  1925          True
Book2   To Kill a Mockingbird           Harper Lee  1960          True
Book3                    1984        George Orwell  1949          True
Book4     Pride and Prejudice          Jane Austen  1813          True
Book5  The Catcher in the Rye        J.D. Salinger  1951          True

## 3. Search & Selection

In [6]:
fitzgerald_books = library_df[library_df["Author"] == "F. Scott Fitzgerald"]

fitzgerald_books

                  Title               Author  Year  Availability
Key
Book1  The Great Gatsby  F. Scott Fitzgerald  1925          True

In [7]:
available_books = library_df[library_df["Availability"] == True]

available_books

                        Title               Author  Year  Availability
Key
Book1        The Great Gatsby  F. Scott Fitzgerald  1925          True
Book2   To Kill a Mockingbird           Harper Lee  1960          True
Book3                    1984        George Orwell  1949          True
Book4     Pride and Prejudice          Jane Austen  1813          True
Book5  The Catcher in the Rye        J.D. Salinger  1951          True